@startuml
class PrivacyModel {
    + PrivacyModel(logger:ILogger<PrivacyModel>)
    + OnGet() : void
}
class "ILogger`1"<T> {
}
PageModel <|-- PrivacyModel
PrivacyModel --> "_logger<PrivacyModel>" "ILogger`1"
@enduml
